title:            keep it https
description:      A no fluff just stuff tech blog
logo:             logo.001.jpg
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
# You don't need to specify the protocol if you want it available on http and https. Example: //localhost:4000
url:              http://localhost:4000

# Jekyll configuration

permalink: /:categories/:title/
lsi: true
markdown: kramdown
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
  - jekyll-gist
include: [".htaccess"]
exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "node_modules", "Gruntfile.js", "package.json", ".jekyll-assets-cache"]

# Plugin: jekyll-assets

assets:
  sources:
    - _assets/javascripts
    - _assets/stylesheets
  baseurl: http://localhost:4000/assets/
  debug: false
  version: 1

# Owner/author information
owner:
  name:           Fabrizio Fortino
  email:          fabrizio.fortino@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        "fabriziofortino"
  facebook:
  github:         "fabriziofortino"
  github-repo:    https://github.com/fabriziofortino/fabriziofortino.github.io/tree/master
  stackexchange:  http://stackoverflow.com/users/1026224/fabrizio-fortino
  linkedin:       "fabriziofortino"
  instagram:
  flickr:
  tumblr:
  google:
    ad-client: ca-pub-5032684030004556
    ad-slot: 2119568483
    analytics:
    plus: https://plus.google.com/109235971620840998869
    verify:
  bing:
    verify:
  alexa:
    verify:
  yandex:
    verify:
  avatar:         profile.jpg
disqus_shortname: fabriziofortino

# Analytics and webmaster tools stuff goes here
google_analytics: UA-20558822-7
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Dublin
future:      true

# Collections

collections:
  faqs:
    output: true
    permalink: /:collection/:path/
    title: FAQs
  components:
    output: false
  colors:
    output: false
